name: Main Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  cicd:
    name: Deploy using aws eks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Confirm aws credentials
        run: |
          aws sts get-caller-identity
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, Tag & Push a Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: myapps/pacman
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f docker/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          echo "Docker image built successfully."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      - name: Create AWS EKS Cluster Access Entry
        run: |
          aws eks create-access-entry \
              --cluster-name pacman-cluster \
              --principal-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions \
              --type STANDARD
      - name: Grant Cluster Permission
        run: |
          aws eks associate-access-policy \
              --cluster-name pacman-cluster \
              --principal-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions \
              --policy-arn arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy \
              --access-scope '{"type": "cluster"}'

      - name: configure eks access
        run: |
          aws eks update-kubeconfig --region eu-central-1 --name pacman-cluster
      - name: Update Kubernetes Deployment
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: myapps/pacman
          IMAGE_TAG: ${{ github.sha }}
        run: |
          kubectl apply -f k8s/storage-class.yaml
          kubectl apply -f k8s/db-sts.yaml
          kubectl apply -f k8s/app-deployment.yaml
          kubectl set image deployment/pacman-app pacman=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          kubectl rollout status deployment pacman-app
          kubectl rollout status statefulset mongo
          kubectl get services pacman-service
